---
title: "NSE-BSE-F-O-Timeseries-Analysis-in-R"
output: html_document
date: "`r Sys.Date()`"
author: "Dhruv Haldar (haldar@kth.se)"
---

### FII & DII TRADING ACTIVITY

```{r fiidii, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, include=TRUE}
#source("nse_bse_data.R", local = knitr::knit_global())
# or sys.source("your-script.R", envir = knitr::knit_global())
packages <- function()
{# Package names
packages <- c("ggplot2", "readxl", "nser", "lattice", 
                "reshape2", 
                #"hablar", 
                "dplyr", 
                #"tidyquant",
                "tidyverse", 
                "scales",
                "padr",
                #"purrr",
                #"svDialogs",
                "utils", 
                "quantmod",
              "broom", 
              #"magrittr",
                "diffr", 
                #"diffobj",
                "alphavantager","plotly",
                "ggpubr",
                #"derivmkts",
                #"TTR",
                "optionstrat",
                #"knitr",
                #"rmarkdown",
              "PerformanceAnalytics",
              "dygraphs",
                "nse2r"
                )
  
# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
    install.packages(packages[!installed_packages])
  }
  
# Packages loading
invisible(lapply(packages, library, character.only = TRUE))
  
# Alpha Vantage API key
api_key="MB7IR06HYB54IUJG"
av_api_key(api_key)
  }

netFIIDIIfn <- function(fdii) #function
{
date = fdii[3:20,1]
date <- gsub("-", "", date)                        # Applying gsub function
date = as.Date(date, "%d%b%y")


net_FII = fdii[3:20,4]
net_FII = factor(net_FII)
net_FII <- gsub(",","", net_FII)                   # Applying gsub function
options(digits=7)
net_FII=as.double(net_FII)

net_DII = fdii[3:20,7]
net_DII = factor(net_DII)
net_DII <- gsub(",","", net_DII)                   # Applying gsub function
options(digits=7)
net_DII=as.double(net_DII)

fdii_main <- data.frame(date,net_FII,net_DII)

#netFII+netDII
fig.align = 'right'
p <- ggplot(fdii_main,
            aes(x = date, y = net_FII+net_DII)) +
  geom_text(aes(label=net_FII+net_DII),
            vjust=0.006,
            size=3.5,
            color="white")+
  scale_x_date(date_labels="%b %d",date_breaks  ="1 day") +
  labs(x = "Date",
       title = "Gross Purchase FII+DII (Crores)",
       y = "Gross Purchase (Crores)",
       subtitle = paste("Last updated",Sys.time()),
       panel.grid.major = element_blank(),
       panel.grid.minor = element_blank()
  )

p+ theme(legend.position="none")

p+ geom_bar(aes(fill = net_FII+net_DII > 0), stat = "identity") +
  scale_fill_manual(
    guide = "none",
    breaks = c(TRUE, FALSE),
    values=c("green", "red"))}


data_bhavtoday_nser <- function() #function
{
  get_data <- function(get_data) 
    {
#FO Bhavcopy Today (updated every evening,not working in weekend)
    fobhavtoday <-- fobhavtoday()

#Indices Data
    fo_indices = fobhavtoday[1:19,]
    }
  get_data2 <- possibly(get_data, otherwise = NA)
}

# FO Bhavcopy Hist. (1 Jan 2016 Onwards)
# Hist_date=28042022
data_bhavtoday_nser <- function() #function
{
  fobhavhist = fobhav(Hist_date)
  bhavhist = bhav(Hist_date)
}

# Heatmap
markets_heatmap <- function() #function
{
  nsetree = nsetree()
}
fo_heatmap <- function() #function
{
  nsetreefo = nsetree("fo")
}

# NSE Indices today
cashmarkets_stocks <- function() #function
{
  nseindex = nseindex()
  nseindex_name = nseindex[1:55,1]
  nseindex_change = nseindex[1:55,4]
  nseindex = nse_index_quote(clean_names = TRUE)

#Stock symbol list
  nsestockcode = nse_stock_code(clean_names = TRUE)

#Stock price
  stock_code="SCHAEFFLER"
  stock_price = nse_stock_quote(stock_code, source = c("yahoo",
                                                       "rediff"))
  print(paste(stock_code,"is trading at",
            stock_price,"INR at NSE",", last updated",Sys.time()))

#52 Week high
  nseyearhigh = nse_stock_year_high(clean_names = TRUE)
#52 Week low
  nseyearlow = nse_stock_year_low(clean_names = TRUE)
#Most Traded Stocks
  nsemosttraded = nse_stock_most_traded(clean_names = TRUE)
#Top Gainers
  nsetopgainers = nse_stock_top_gainers(clean_names = TRUE)
#Top Losers
  nsetoplosers = nse_stock_top_losers(clean_names = TRUE)
}

jugaad_data <- function() #function
{ 
  #date_df= df[1:12625,1]
  #price_df= df[1:12625,2]
  #dateprice_df <- data.frame(date_df,price_df)
  }

##Data 
#symbol="MARUTI" #fix in python file

#Function Calls
packages()
fdii = fdii()
netFIIDIIfn(fdii)
#fo_heatmap()
#markets_heatmap()
#data_bhavtoday_nser()
#cashmarkets_stocks()
#EOC
```

## Preopen NSE FO Markets
### <span style="color: green;">NSE FO Top Gainers</span> 
```{r nse_fo_top_gainers, echo=FALSE, error=FALSE, warning=FALSE, paged.print=FALSE, results='asis', tidy=TRUE}
#NSE Markets
#library(nse2r)
options(warn=-1) #supress coercion warnings, fix later
  #nseopen_fo = nseopen("fo") #FO stocks
knitr::kable(nse_fo_top_gainers(clean_names = TRUE))
```

### <span style="color: red;">NSE FO Top Losers</span> 
```{r nse_fo_top_losers, echo=FALSE, error=FALSE, warning=FALSE, paged.print=FALSE, results='asis', tidy=TRUE}
knitr::kable(nse_fo_top_losers(clean_names = TRUE))
```

## NSE Indices (Preopen Nifty, Nifty Bank disabled)
```{r nse_preopen_nifty, echo=FALSE, error=FALSE, warning=FALSE, paged.print=FALSE, results='asis', tidy=TRUE}
#knitr::kable(nse_preopen_nifty(clean_names = TRUE)) #preopen NIFTY
#knitr::kable(nse_preopen_nifty_bank(clean_names = TRUE)) #preopen NIFTYBK
knitr::kable(nse_index_quote(clean_names = TRUE))
```

## Most Traded Stocks
```{r nse_most_traded, echo=FALSE, error=FALSE, warning=FALSE, paged.print=FALSE, results='asis', tidy=TRUE}
knitr::kable(nse_stock_most_traded(clean_names = TRUE))
```

## NSE IPO  
```{r nse_ipo, echo=FALSE, error=FALSE, warning=FALSE, paged.print=FALSE, results='asis', tidy=TRUE}
#knitr::kable(nselive()) #Nifty stocks
knitr::kable(nseipo()) #ipo
```

## NSE Cash Market
```{r nse_cash_mrkt, echo=FALSE, error=FALSE, warning=FALSE, paged.print=FALSE, results='asis', tidy=TRUE}
print("52 Week high")
knitr::kable(nse_stock_year_high(clean_names = TRUE))
print("52 Week low")
knitr::kable(nse_stock_year_low(clean_names = TRUE))
print("Top Gainers")
knitr::kable(nse_stock_top_gainers(clean_names = TRUE))
print("Top Losers")
knitr::kable(nse_stock_top_losers(clean_names = TRUE))
```  

## RBI Current Data
```{python rbi, include=TRUE, echo=FALSE, tidy=TRUE}
def rbi():
  from jugaad_data.rbi import RBI
  r = RBI()
  print(r.current_rates())
rbi()
```

## NSE FO Heatmap (disabled)
```{r nse_fo_heatmp, echo=FALSE, error=FALSE, warning=FALSE, paged.print=FALSE, results='hold', tidy=TRUE}
#nsetree("fo")
```  
## Stock Price Chart
```{python jugaad-data, include=TRUE, echo=FALSE, tidy=TRUE}

from datetime import datetime
from requests import Session
import pandas as pd
#import click
#mport csv

page_url = "https://www.nseindia.com/get-quotes/equity?symbol=LT"
chart_data_url = "https://www.nseindia.com/api/chart-databyindex"

s = Session()
h = {"user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
     "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-GB,en-US;q=0.9,en;q=0.8",
    }
s.headers.update(h)
r = s.get(page_url)

def fetch_data(symbol):
    data = {"index": symbol + "EQN"}
    r = s.get(chart_data_url, params=data)
    data = r.json()['grapthData']
    return [[datetime.utcfromtimestamp(d[0]/1000),d[1]] for d in data]
symbol="SJVN"
d = fetch_data('SJVN')
print(symbol)
df = pd.DataFrame(d)
df.columns = ['Time', "Price"]
df.index = df['Time'].dt.time
df['Price'].plot(figsize=(12,6), grid=True)

#print(df)
```
```{r stock_portfolio, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, include=TRUE}
monthly_returns <- function(ticker, base_year)
{
  # Obtain stock price data from Yahoo! Finance
  stock <- getSymbols(ticker, src = "yahoo", auto.assign = FALSE) 
  # Remove missing values
  stock <- na.omit(stock)
  # Keep only adjusted closing stock prices
  stock <- stock[, 6]
  
  # Confine our observations to begin at the base year and end at the last available trading day
  horizon <- paste0(as.character(base_year), "/", as.character(Sys.Date()))
  stock <- stock[horizon]
  
  # Calculate monthly arithmetic returns
  data <- periodReturn(stock, period = "monthly", type = "arithmetic")
  
  # Assign to the global environment to be accessible
  assign(ticker, data, envir = .GlobalEnv)
}

# Call our function for each stock
monthly_returns("SBUX", 2015)
monthly_returns("CCL", 2015)
monthly_returns("AAPL", 2015)

# Get S&P 500 Data
monthly_returns("SPY", 2015)

# Merge all the data and rename columns
returns <- merge.xts(SBUX, CCL, AAPL, SPY)
colnames(returns) <- c("SBUX", "CCL", "AAPL", "SP500")

# Produce interactive chart of stock returns
dygraph(returns, main = "Starbucks vs. Carnival vs. Apple vs. S&P 500") %>%
  dyAxis("y", label = "Return", valueRange = c(-1,0.5)) %>%
  dyRangeSelector(dateWindow = c("2015-01-01", "2020-07-01")) %>%
  dyOptions(colors = RColorBrewer::brewer.pal(4, "Set2")) 

# Print last 5 rows of the data, rounded to 4 decimal places
round(tail(returns, n = 5), 4)

# Assign weights
wts <- c(1/3, 1/3, 1/3)

# Construct a portfolio using our returns object and weights
# Only select first three columns to isolate our individual stock data
portfolio_returns <- Return.portfolio(R = returns[,1:3], weights = wts, wealth.index = TRUE)

# Then isolate our S&P 500 data
benchmark_returns <- Return.portfolio(R = returns[,4], wealth.index = TRUE)

# Merge the two
comp <- merge.xts(portfolio_returns, benchmark_returns)
colnames(comp) <- c("Portfolio", "Benchmark")

# Build an interactive graph to compare performance
dygraph(comp, main = "Portfolio Performance vs. Benchmark") %>%
  dyAxis("y", label = "Amount ($)")
```