---
title: "removedcode"
output: html_document
date: "`r Sys.Date()`"
---

```{r nse_fo_top_gainers, eval=FALSE, error=FALSE, message=FALSE, warning=FALSE, escape=, include=FALSE}
#options(warn=-1) #supress coercion warnings, fix later
#nseopen_fo = nseopen("fo") #FO stocks
knitr::kable(nse_fo_top_gainers(clean_names = TRUE))%>%
  kable_styling(bootstrap_options = "condensed",
                full_width = F
                ,font_size = 12,
                fixed_thead = T)%>%
scroll_box(width = "100%", height = "600px")
```

### <span style='color: #FC5130'> NSE FO Top Losers

```{r nse_fo_top_losers, eval=FALSE, error=FALSE, message=FALSE, warning=FALSE, include=FALSE}
knitr::kable(nse_fo_top_losers(clean_names = TRUE))%>%
  kable_styling(bootstrap_options = "condensed",
                , full_width = F
                ,font_size = 12,
                fixed_thead = T)%>%
scroll_box(width = "100%", height = "600px")
```

## <span style='color: #1d7874'> NSE Indices

### Preopen Nifty

```{r nse_preopen_nifty, eval=FALSE, error=FALSE, message=FALSE, warning=FALSE, include=FALSE}
knitr::kable(nse_preopen_nifty(clean_names = TRUE))%>% #preopen NIFTY
  kable_styling(bootstrap_options = "condensed",
                , full_width = F
                ,font_size = 12,
                fixed_thead = T)%>%
scroll_box(width = "100%", height = "600px")
```

### Preopen Nifty Bank

```{r nse_preopen_niftybk, eval=FALSE, error=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE, results='asis', tidy=TRUE}
knitr::kable(nse_preopen_nifty_bank(clean_names = TRUE))%>% #preopen 
  kable_styling(bootstrap_options = "condensed",
                , full_width = F
                ,font_size = 12,
                fixed_thead = T)%>%
scroll_box(width = "100%", height = "50%")
```

### NSE Index

```{r nse_index, eval=FALSE, error=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE, results='asis', tidy=TRUE}
knitr::kable(nse_index_quote(clean_names = TRUE))%>%
  kable_styling(bootstrap_options = "condensed",
                , full_width = F
                ,font_size = 12,
                fixed_thead = T)%>%
scroll_box(width = "50%", height = "200px")
```

## <span style='color: #1d7874'> Most Traded Stocks {#span-stylecolor-1d7874-most-traded-stocks}

```{r nse_most_traded, eval=FALSE, error=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE, results='asis', tidy=TRUE}
knitr::kable(nse_stock_most_traded(clean_names = TRUE))%>%
  kable_styling(bootstrap_options = "condensed",
                , full_width = F
                ,font_size = 12,
                fixed_thead = T)%>%
scroll_box(width = "80%", height = "50%")
```

## <span style='color: #1d7874'>NSE IPO

```{r nse_ipo, eval=FALSE, error=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE, results='asis', tidy=TRUE}
#knitr::kable(nselive()) #Nifty stocks
knitr::kable(nseipo())%>%
  kable_styling(bootstrap_options = "condensed",
                , full_width = F
                ,font_size = 12,
                fixed_thead = T)
```

## <span style='color: #1d7874'>NSE Cash Market

### 52 Week high

```{r 52wkhigh, eval=FALSE, error=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE, results='asis', tidy=TRUE}
knitr::kable(nse_stock_year_high(clean_names = TRUE))%>%
  kable_styling(bootstrap_options = "condensed",
                , full_width = F
                ,font_size = 12,
                fixed_thead = T)%>%
scroll_box(width = "100%", height = "600px")
```

### 52 Week low

```{r 52wklow, echo=FALSE, error=FALSE, warning=FALSE, paged.print=FALSE, results='asis', tidy=TRUE}
knitr::kable(nse_stock_year_low(clean_names = TRUE))%>%
  kable_styling(bootstrap_options = "condensed",
                , full_width = F
                ,font_size = 12,
                fixed_thead = T)%>%
scroll_box(width = "100%", height = "600px")
```

### Top Gainers

```{r topgainers, echo=FALSE, error=FALSE, warning=FALSE, paged.print=FALSE, results='asis', tidy=TRUE}
knitr::kable(nse_stock_top_gainers(clean_names = TRUE))%>%
  kable_styling(bootstrap_options = "condensed",
                , full_width = F
                ,font_size = 12,
                fixed_thead = T)%>%
scroll_box(width = "100%", height = "400px")
```

### Top Losers

```{r toplosers, echo=FALSE, error=FALSE, warning=FALSE, paged.print=FALSE, results='asis', tidy=TRUE}
knitr::kable(nse_stock_top_losers(clean_names = TRUE))%>%
  kable_styling(bootstrap_options = "condensed",
                , full_width = F
                ,font_size = 12,
                fixed_thead = T)%>%
scroll_box(width = "100%", height = "400px")
```

```{python nifty_pe_python, include=TRUE, echo=FALSE, tidy=TRUE}
#Python Nifty PE Script
#pip install nsepy
from datetime import date
# Index P/E ratio history
from nsepy import get_index_pe_history
nifty_pe = get_index_pe_history(symbol="NIFTY",
                                start=date(2022,1,1),
                                end=date(2022,5,9))
```

## NIFTY PE

```{r nifty_pe_r, echo=FALSE, error=FALSE, warning=FALSE, paged.print=FALSE, results='asis', tidy=TRUE}
pythonr <- py$nifty_pe
# library(pander)
# pander(pythonr)
knitr::kable(pythonr)%>%
  kable_styling(bootstrap_options = "condensed",
                , full_width = F
                ,font_size = 12,
                fixed_thead = T)%>%
scroll_box(width = "170px", height = "350px")
```

## <span style='color: #1d7874'>RBI Current Data

```{python rbidata_python, include=TRUE, echo=FALSE, tidy=TRUE}
from jugaad_data.rbi import RBI
r = RBI()
rbi = r.current_rates()
```

```{r rbidata_r, echo=FALSE, error=FALSE, warning=FALSE, paged.print=FALSE, results='hold', tidy=TRUE}
python_rbi_value <- py$rbi
python_rbi_value[8:11] <- NULL
python_rbi_value[22:23] <- NULL
python_rbi_value <- unlist(python_rbi_value)

knitr::kable(python_rbi_value,
             col.names = c("Values"))%>%
  kable_styling(bootstrap_options = "condensed",
                , full_width = T
                ,font_size = 12,
                fixed_thead = T)%>%
scroll_box(width = "310px", height = "600px")
```

```{r , include=TRUE, echo=FALSE, tidy=TRUE}
py$symbol <- "INFY"
```

## <span style='color: #1d7874'> `r py$symbol` Stock Price Chart

```{python , include=TRUE, include=FALSE, tidy=TRUE}

from datetime import datetime
from requests import Session
import pandas as pd
#import click
#mport csv

page_url = "https://www.nseindia.com/get-quotes/equity?symbol=LT"
chart_data_url = "https://www.nseindia.com/api/chart-databyindex"

s = Session()
h = {"user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
     "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-GB,en-US;q=0.9,en;q=0.8",
    }
s.headers.update(h)
r = s.get(page_url)
#symbol = "INFY"

def fetch_data(symbol):
    data = {"index": symbol + "EQN"}
    r = s.get(chart_data_url, params=data)
    data = r.json()['grapthData']
    return [[datetime.utcfromtimestamp(d[0]/1000),d[1]] for d in data]
d = fetch_data(symbol)
df = pd.DataFrame(d)
df.columns = ['Time', "Price"]
df.index = df['Time'].dt.time
#df['Price'].plot(figsize=(12,6), grid=True)

```
## R version
```{r jugaad-data_r, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, tidy=TRUE}
## Visualize
library(reticulate)
library(tidyverse)
library(tidyquant) 
pydf <- py$df
pydf_date <- py$df[1:1752,1]
pydf_price <- py$df[1:1752,2]
pydf <- data.frame(pydf_date,pydf_price)

# Plot with tidyquant theme and colors
pydf %>%
    ggplot(aes(x = pydf_date, y = pydf_price)) +
    geom_line() +
    labs(title = paste(py$symbol,"Line Chart"), y = "Closing Price", x = "") +
    theme_tq() +
    scale_color_tq()
```

## Stock Portfolio

```{r stock_portfolio, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, include=TRUE}
monthly_returns <- function(ticker, base_year)
{
  # Obtain stock price data from Yahoo! Finance
  stock <- getSymbols(ticker, src = "yahoo", auto.assign = FALSE) 
  # Remove missing values
  stock <- na.omit(stock)
  # Keep only adjusted closing stock prices
  stock <- stock[, 6]
  
  # Confine our observations to begin at the base year and end at the last available trading day
  horizon <- paste0(as.character(base_year), "/", as.character(Sys.Date()))
  stock <- stock[horizon]
  
  # Calculate monthly arithmetic returns
  data <- periodReturn(stock, period = "monthly", type = "arithmetic")
  
  # Assign to the global environment to be accessible
  assign(ticker, data, envir = .GlobalEnv)
}

# Call our function for each stock
monthly_returns("SBUX", 2015)
monthly_returns("CCL", 2015)
monthly_returns("AAPL", 2015)

# Get S&P 500 Data
monthly_returns("SPY", 2015)

# Merge all the data and rename columns
returns <- merge.xts(SBUX, CCL, AAPL, SPY)
colnames(returns) <- c("SBUX", "CCL", "AAPL", "SP500")

# Produce interactive chart of stock returns
dygraph(returns, main = "Starbucks vs. Carnival vs. AAPL vs. S&P 500") %>%
  dyAxis("y", label = "Return", valueRange = c(-1,0.5)) %>%
  dyRangeSelector(dateWindow = c("2015-01-01", "2020-07-01")) %>%
  dyOptions(colors = RColorBrewer::brewer.pal(4, "Set2")) 

# Print last 5 rows of the data, rounded to 4 decimal places
round(tail(returns, n = 5), 4)

# Assign weights
wts <- c(1/3, 1/3, 1/3)

# Construct a portfolio using our returns object and weights
# Only select first three columns to isolate our individual stock data
portfolio_returns <- Return.portfolio(R = returns[,1:3], weights = wts, wealth.index = TRUE)

# Then isolate our S&P 500 data
benchmark_returns <- Return.portfolio(R = returns[,4], wealth.index = TRUE)

# Merge the two
comp <- merge.xts(portfolio_returns, benchmark_returns)
colnames(comp) <- c("Portfolio", "Benchmark")

# Build an interactive graph to compare performance
dygraph(comp, main = "Portfolio Performance vs. Benchmark") %>%
  dyAxis("y", label = "Amount ($)")
```

## Implement later <https://stackoverflow.com/questions/32906263/how-to-knit-pdf-from-rmd-script-by-clicking-an-executable-r-file>

## NSE Fundamentals

```{python nsefundamentals, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}

# #pip3 install websocket-client
# import websocket
# 
# def on_message(ws, message):
#     print(message)
# 
# def on_error(ws, error):
#     print(error)
# 
# def on_close(ws):
#     print("### closed ###")
# 
# def on_open(ws):
#     ws.send('{"type":"subscribe","symbol":"AAPL"}')
#     ws.send('{"type":"subscribe","symbol":"AMZN"}')
#     ws.send('{"type":"subscribe","symbol":"BINANCE:BTCUSDT"}')
#     ws.send('{"type":"subscribe","symbol":"IC MARKETS:1"}')
# 
# if __name__ == "__main__":
#     websocket.enableTrace(True)
#     ws = websocket.WebSocketApp("wss://ws.finnhub.io?token=c9ses3iad3i4aps1t52g",
#                               on_message = on_message,
#                               on_error = on_error,
#                               on_close = on_close)
#     ws.on_open = on_open
#     ws.run_forever()

```
